# Generated by Django 5.0.3 on 2025-04-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
